services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_MEIN_BE_BASE_URL: http://localhost:4000/backend/

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://mein_user:mein_password@db:5432/mein_db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
